### PR TITLE
Adjustments and configurability to support Qt 3D

### PR DESCRIPTION
**Pull request by er-vin**
Hello,

I'm trying to get complete coverage of Qt 3D through the rust bindings. It happens to do a couple of things differently from other Qt modules which requires a few changes to get it to a usable state. It still requires quite some unsafe blocks in the user code but at least now I can write something which ends up on screen.

Regards.

### CODE REVIEW

**Comment by Riateche** [comment]
Nice work! I'm currently away, so I will be able to review the changes in
about a week. Meanwhile, if you've got some working code, it would be nice
to add it to the crate templates as examples or tests.

**Comment by er-vin** [comment]
Alright, I'll try to add that this week. I might be busy though for the coming two weeks, so I might be a bit unresponsive.

**Comment by Riateche** [comment]
Everything seems to be fine. Thanks for the contribution! Feel free to add tests or examples as a separate pull request when you have time.

**Comment by er-vin** [comment]
Excellent, thanks! Yes, adding an example is still on my TODO list, I'm sure I'll be able to stay in place long enough at one point to contribute it...

**Pull request merged**
